"""Actualiza el onboarding con contenido mínimo y fuentes para organizadores."""
from pathlib import Path
import re, html, runpy

ROOT=Path(__file__).resolve().parent
S={
 'programa':('Programa CNCF','https://github.com/cncf/communitygroups/blob/main/README.md'),
 'organizadores':('Guía de organizadores','https://github.com/cncf/communitygroups/blob/main/organizers.md'),
 'practicas':('Guía de eventos','https://github.com/cncf/communitygroups/blob/main/best_practices.md'),
 'conducta':('Código de conducta','https://github.com/cncf/foundation/blob/main/code-of-conduct.md'),
 'jurisdiccion':('Alcance y reportes','https://www.cncf.io/conduct/faq/'),
 'marca':('Marca de comunidades','https://github.com/cncf/communitygroups/blob/main/branding.md'),
 'antitrust':('Antitrust LF','https://www.linuxfoundation.org/legal/antitrust-policy'),
 'politica':('Neutralidad política','https://www.cncf.io/political-neutrality-policy/'),
 'politicas':('Índice de políticas CNCF','https://www.cncf.io/policies/'),
}
paths={
 'people':'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',
 'book':'<path d="M3 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-3H3zM21 4h-6a3 3 0 0 0-3 3v14a4 4 0 0 1 4-3h5z"/>',
 'heart':'<path d="M12 21 3.5 12.5A5.5 5.5 0 0 1 12 5.5a5.5 5.5 0 0 1 8.5 7z"/>',
 'shield':'<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6zM8 12l3 3 5-6"/>',
 'calendar':'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18m-13 5h3m3 0h3"/>',
 'mic':'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8"/>',
 'check':'<path d="m4 12 5 5L20 6"/>',
 'key':'<circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-5-5 3-3m-1 5 3-3"/>',
 'globe':'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 'balance':'<path d="M12 3v18m-5 0h10M3 7h18M6 7l-4 8h8zm12 0-4 8h8z"/>',
 'mail':'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
 'flag':'<path d="M5 22V3h13l-3 5 3 5H5"/>',
 'link':'<path d="m9 15 6-6m-5-4 2-2a5 5 0 0 1 7 7l-3 3m-2 6-2 2a5 5 0 0 1-7-7l3-3"/>',
 'school':'<path d="m2 8 10-5 10 5-10 5zM6 10v7c4 3 8 3 12 0v-7m4-2v8"/>',
 'lock':'<rect x="4" y="10" width="16" height="12" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 5v3"/>',
 'chart':'<path d="M3 3v18h18M7 17v-5m5 5V7m5 10V4"/>',
}
def icon(name):return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[name]+'</svg>'
def cards(items):
 return '<div class="tiles cols-'+str(len(items))+'">'+''.join('<article class="tile">'+icon(i)+'<h3>'+h+'</h3><p>'+b+'</p></article>' for i,h,b in items)+'</div>'
def flow(items):return '<div class="flow">'+''.join('<div class="flow-step"><span class="stepno">'+str(n)+'</span>'+icon(i)+'<h3>'+h+'</h3><p>'+b+'</p></div>' for n,(i,h,b) in enumerate(items,1))+'</div>'
def sources(keys):return ' · '.join('<a href="'+S[k][1]+'" target="_blank" rel="noopener">'+S[k][0]+' ↗</a>' for k in keys)

slides=[]
def add(title,headline,body,kind='Práctica local propuesta',refs=(),note='',dark=False):slides.append((title,headline,body,kind,refs,note,dark))
add('Bienvenida','Organizar es<br><em>hacer comunidad.</em>', '<div class="welcome-lockup"><img src="{{LOGO}}" alt="Cloud Native Lima"><div class="audience">ONBOARDING<br><strong>Nuevos organizadores</strong></div></div>', 'Cloud Native Lima · equipo organizador',note='Sesión de inducción para quienes organizarán actividades. Objetivo: salir con responsabilidades, lectura de políticas y una primera tarea acordada. Los cuadros marcados como práctica local son propuestas para el equipo de Lima, no requisitos de CNCF.')
add('Objetivos','Nuestro trabajo, <em>en tres verbos.</em>',cards([('book','Enseñar','Experiencias útiles'),('people','Conectar','Personas y universidades'),('heart','Cuidar','Una comunidad sostenible')]),note='Traducir los objetivos en resultados concretos: una práctica que funcione, una nueva persona que se integre y un equipo que pueda sostener el calendario. No usar únicamente inscripciones como medida de éxito.')
add('Equipo','Liderazgo <em>compartido.</em>','<div class="metrics"><article><strong>2+</strong><h3>Organizadores</h3><p>Recomendación del programa</p></article><article><strong>≤50%</strong><h3>De una empresa</h3><p>Composición del equipo</p></article><article><strong>≤2</strong><h3>Grupos por organizador</h3><p>Límite del programa</p></article></div>','Guía CNCF · recomendaciones y límites',('organizadores',),'La guía recomienda dos o más personas y, como ideal, hasta siete para grupos presenciales o cinco virtuales; las excepciones para capítulos amplios están en el documento. Todos son líderes: repartir funciones sin asumir una jefatura. Revisar también el criterio de residencia o presencia local durante al menos la mitad del año.')
add('Alta de organizadores','El alta tiene <em>un proceso.</em>',flow([('people','Acordar','Con el equipo'),('link','Solicitar','Issue en GitHub'),('check','Confirmar','Términos y respaldo'),('key','Habilitar','Accesos por rol')]),'CNCF: alta · Lima: entrega de accesos',('organizadores',),'Dos rutas: el equipo presenta la solicitud y la persona comenta aceptando los términos; o la persona la presenta y al menos 50% de organizadores confirma su incorporación. La entrega de accesos es una práctica local posterior a la confirmación correspondiente; no se realiza automáticamente con esta presentación. Las bajas también se tramitan por issue y confirmación de la persona.')
add('Responsabilidades','Una función. <em>Un responsable y respaldo.</em>',cards([('mic','Contenido','Ponentes · revisión'),('calendar','Producción','Sede · equipos'),('people','Comunidad','Difusión · bienvenida'),('link','Alianzas','Universidades · apoyos')]),note='Asignar nombres y respaldo antes de cada actividad. Las funciones son una propuesta local. Añadir responsables explícitos de convivencia y finanzas; pueden ser tareas compartidas con las funciones visibles. Registrar acuerdos y entregar accesos por invitación, sin compartir contraseñas.')
add('Reglas del programa','La base de <em>cada meetup.</em>',cards([('heart','Gratuito','Entrada sin cobro'),('globe','OCGroups','Registro del evento'),('calendar','Actividad','No superar 90 días'),('balance','Neutralidad','Contenido independiente')]),'Requisitos del programa CNCF',('programa','practicas'),'La guía exige registro en Open Community Groups y entrada gratuita en los meetups. El README define inactividad al superar 90 días sin eventos. No confundir ese umbral con las condiciones de incentivos: tienen criterios adicionales. La neutralidad debe mantenerse incluso cuando existe patrocinio; su incumplimiento puede conducir a desactivación.',True)
add('Código de conducta','Respeto. <em>Sin excepciones.</em>',cards([('people','Inclusión','Respeta identidades'),('shield','Sin acoso','Ni represalias'),('lock','Privacidad','No divulgar datos')]),'Código de conducta CNCF',('conducta',),'El código cubre espacios y actividades comunitarias, además de conductas dirigidas a participantes en ese contexto. Prohíbe acoso, amenazas, divulgación de información privada sin permiso y represalias. Como organizadores debemos conocerlo y hacerlo visible en nuestras actividades.')
add('Reporte de incidentes','Escuchar → <em>proteger → reportar.</em>',flow([('heart','Escucha','Con discreción'),('shield','Protege','Atiende la seguridad'),('mail','Reporta','Canal correspondiente')])+'<a class="report" href="mailto:conduct@cncf.io">conduct@cncf.io ↗</a>','Canal CNCF · respuesta local propuesta',('conducta','jurisdiccion'),'Para incidentes comunitarios transversales, el código indica conduct@cncf.io. Kubernetes dispone de conduct@kubernetes.io; los eventos producidos por LF usan eventconduct@cncf.io. Un meetup local no es automáticamente un evento producido por LF. Ante peligro inmediato, priorizar seguridad y ayuda de emergencia. Escuchar en privado y conservar información pertinente; no prometer secreto absoluto ni investigar públicamente. La resolución corresponde al equipo con jurisdicción.')
add('Patrocinios','Apoyo con <em>independencia.</em>',cards([('link','Apoyo','Sede · logística'),('book','Contenido','Revisar las charlas'),('balance','Transparencia','Acordar y registrar')]),'Guía CNCF + gestión local',('practicas',),'La guía recomienda revisar presentaciones para evitar discursos de venta y agradecer a patrocinadores. Recomienda no darles más de quince minutos de escenario ni convertirlos en el contenido principal. Propuesta local: documentar aportes, gastos y compromisos; cualquier acceso a datos requiere una revisión separada y no se ofrece como contraprestación automática.')
add('Otras políticas','También debemos <em>conocer estos límites.</em>',cards([('balance','Competencia','No coordinar precios'),('flag','Neutralidad política','Foco en la misión'),('lock','Datos personales','Respetar permisos')]),'Políticas oficiales CNCF / LF',('antitrust','politica','conducta'),'Antitrust: no intercambiar estrategias comerciales sensibles, repartir mercados ni coordinar precios. Usar agenda y actas; si una conversación infringe la política, objetar, retirarse si continúa y dejar constancia o informar al canal legal indicado. La neutralidad política limita campañas ajenas a cloud native; inclusión y accesibilidad tecnológicas sí están alineadas con la misión. Para privacidad, el código prohíbe divulgar información privada sin permiso explícito.')
add('Identidad','Identidad local. <em>Marcas cuidadas.</em>',cards([('globe','Nombre','Cloud Native Lima'),('heart','Identidad','Referencia a la ciudad'),('shield','Marcas ajenas','Sin alteraciones')]),'Guía de marca de comunidades',('marca',),'La guía permite referencias locales y promueve el símbolo común del programa. El nombre recomendado es Cloud Native + ciudad; no usar CNCF como nombre del capítulo. No alterar logos de proyectos; la guía especifica enlazar a sus sitios cuando se usan. Nuestro logo es una propuesta local, no una marca oficial de CNCF ni una aprobación de CNCF. University se presenta como actividad local, sin prometer certificación o acreditación.')
add('Ciclo del evento','Un evento, <em>cuatro momentos.</em>',flow([('calendar','Preparar','Objetivo · sede'),('mic','Validar','Charla · equipos'),('people','Realizar','CoC · asistencia'),('chart','Mejorar','Recursos · retro')]),'Operación local basada en la guía',('practicas',),'Antes de publicar: confirmar responsable, sede, ponentes y presupuesto. Verificar accesibilidad, conectividad y cupo. En la apertura: explicar convivencia, contacto del equipo y tratamiento de fotografías. Después: compartir materiales, contar asistentes reales y hacer retrospectiva. Fechas sugeridas para Lima: preparar cuatro semanas antes y cerrar el seguimiento durante la semana posterior.')
add('Cloud Native University','University: <em>conectar con el campus.</em>',cards([('school','Docente enlace','Objetivo y público'),('book','Práctica guiada','Nivel y requisitos'),('people','Continuidad','Próxima actividad')]),note='Propuesta operativa de Lima para University. Confirmar enlace docente, permisos de sede, accesibilidad y facilitadores; probar el laboratorio y ofrecer alternativa guiada. Medir participación y aprendizaje. No presentar una universidad como aliada hasta acordarlo ni ofrecer certificaciones oficiales sin respaldo.')
add('Primeros 30 días','Tu primer mes <em>organizando.</em>',flow([('book','Leer','Políticas y guías'),('key','Preparar','Rol y accesos'),('people','Acompañar','Un evento del equipo'),('check','Asumir','Una tarea y retro')]),note='Ruta interna sugerida: leer documentos, resolver dudas con el equipo, confirmar incorporación, recibir accesos necesarios y asumir una tarea acotada con respaldo. La disponibilidad real de eventos determina el ritmo. Al cerrar, verificar lectura, rol, responsable de acompañamiento y próximo compromiso.',dark=True)
add('Lecturas y contactos','Antes de organizar, <em>lee las fuentes.</em>','<div class="reading-grid">'+''.join('<a href="'+S[k][1]+'" target="_blank" rel="noopener">'+icon(i)+'<span>'+label+'</span><b>↗</b></a>' for k,i,label in [('organizadores','people','Organizadores'),('programa','globe','Programa'),('conducta','shield','Código de conducta'),('practicas','calendar','Eventos'),('marca','flag','Marca'),('politicas','book','Políticas CNCF')])+'</div><div class="contact-line">Programa: <a href="mailto:community-groups@cncf.io">community-groups@cncf.io</a></div>','Fuentes oficiales · consultadas 25/09/2026',(), 'Las fuentes enlazadas son la referencia vigente; esta presentación es una síntesis de inducción, no sustituye su lectura completa. Para dudas operativas, el programa indica #community-group-organizers en Slack o community-groups@cncf.io. Las reglas de TCG y KCD no se trasladan automáticamente a un grupo regional. Antes del primer evento, el equipo local debe acordar responsables, contactos y herramientas.')

sections=[]
for n,(title,headline,body,kind,refs,note,dark) in enumerate(slides,1):
 sections.append(f'<section class="slide organizer {"dark" if dark else ""}" data-title="{html.escape(title)}" aria-labelledby="title-{n}" {"hidden" if n>1 else ""}><p class="eyebrow">{n:02d} / ORGANIZADORES</p><h2 id="title-{n}">{headline}</h2><div class="organizer-content">{body}</div><div class="bottomline"><span>{kind}</span><span class="source-links">{sources(refs)}</span></div><template class="speaker-note"><h3>{title}</h3><p>{html.escape(note)}</p><p>{sources(refs)}</p></template></section>')

file=ROOT/'onboarding.template.html'
base=(ROOT/'onboarding-integrantes-anterior.template.html').read_text() if (ROOT/'onboarding-integrantes-anterior.template.html').exists() else file.read_text()
if not (ROOT/'onboarding-integrantes-anterior.template.html').exists():
 (ROOT/'onboarding-integrantes-anterior.template.html').write_text(base)
base=re.sub(r'<main class="stage".*?</main>','<main class="stage" id="deck" aria-label="Onboarding de nuevos organizadores">'+''.join(sections)+'</main>',base,flags=re.S)
base=base.replace('Bienvenida · Cloud Native Lima','Organizadores · Cloud Native Lima').replace('Bienvenida a la comunidad','Onboarding de organizadores')
base=base.replace('aria-valuemax="11"','aria-valuemax="15"').replace('01 / 11','01 / 15')
base=re.sub(r'<meta name="description"[^>]+>','<meta name="description" content="Onboarding visual para organizadores de Cloud Native Lima, con requisitos del programa y fuentes oficiales CNCF.">',base)
if 'id="notes"' not in base:base=base.replace('<div class="tools">','<div class="tools"><button class="tool" id="notes">Notas y fuentes</button>')
extra='''
.organizer h2{font-size:clamp(36px,4.3vw,64px);max-width:1100px}.organizer-content{flex:1;display:flex;flex-direction:column;justify-content:center}.tiles{display:grid;gap:20px}.cols-3{grid-template-columns:repeat(3,1fr)}.cols-4{grid-template-columns:repeat(4,1fr)}.tile{border:1px solid #d9dfdf;border-radius:14px;padding:30px 25px;min-height:210px;background:#ffffff65}.tile svg{width:42px;height:42px;color:var(--blue);margin-bottom:24px}.tile h3{font-size:26px;margin-bottom:10px}.tile p{font-size:17px;color:var(--muted);margin:0;line-height:1.4}.dark .tile{background:#182b43;border-color:#31465e}.dark .tile svg{color:var(--mint)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.metrics article{border-top:2px solid var(--blue);padding-top:22px}.metrics strong{font-size:85px;letter-spacing:-4px;color:var(--blue)}.metrics h3{font-size:25px;margin-top:12px}.metrics p{font-size:15px;color:var(--muted)}.flow{display:grid;grid-auto-columns:1fr;grid-auto-flow:column;gap:22px}.flow-step{border:1px solid #d9dfdf;border-radius:12px;padding:25px 18px;position:relative}.flow-step:not(:last-child):after{content:'→';position:absolute;right:-20px;top:45%;color:var(--blue);font-size:21px}.flow-step svg{width:34px;height:34px;color:var(--blue);display:block;margin:20px 0}.stepno{font-size:12px;font-weight:700;color:var(--muted)}.flow-step h3{font-size:23px}.flow-step p{font-size:16px;color:var(--muted);margin:0}.dark .flow-step{border-color:#3b4c60}.dark .flow-step svg,.dark .flow-step:after{color:var(--mint)}.report{font-size:25px;font-weight:700;color:var(--blue);align-self:center;margin-top:30px}.welcome-lockup{display:flex;align-items:center;gap:60px}.welcome-lockup img{width:48%;max-width:500px}.audience{font-size:12px;letter-spacing:2px;color:var(--muted);line-height:2}.audience strong{font-size:25px;letter-spacing:-.5px;color:var(--navy)}.reading-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.reading-grid>a{display:flex;align-items:center;gap:14px;padding:24px 20px;border:1px solid #d9dfdf;border-radius:10px;text-decoration:none;font-size:17px}.reading-grid svg{width:26px;height:26px;color:var(--blue)}.reading-grid b{margin-left:auto;color:var(--blue)}.contact-line{font-size:17px;margin-top:25px}.source-links{font-size:10px;text-align:right;max-width:50%;line-height:1.6}.bottomline{gap:15px}.bottomline>span:first-child{max-width:55%}dialog{width:min(700px,90vw);max-height:80vh;border:0;border-radius:16px;padding:30px;color:var(--navy);background:var(--paper);box-shadow:0 20px 100px #0004}dialog::backdrop{background:#101e3580}dialog p{line-height:1.65;font-size:17px}dialog a{color:var(--blue)}dialog button{float:right;padding:8px 14px;border:1px solid #bcc5cf;background:transparent;border-radius:7px}.dialog-heading{padding-top:20px}.organizer .eyebrow{margin-bottom:20px}
@media screen and (min-width:701px) and (max-height:850px){.organizer h2{font-size:46px}.tile{padding:23px 20px;min-height:180px}.tile svg{margin-bottom:18px}.tile h3{font-size:24px}.flow-step{padding:20px 17px}.metrics strong{font-size:76px}.reading-grid>a{padding:19px}}
@media(max-width:700px){.top{height:auto;min-height:75px;flex-wrap:wrap;padding:10px 0;gap:8px}.tools{flex-wrap:wrap}.organizer{min-height:640px}.organizer h2{font-size:37px}.organizer-content{padding-top:30px;gap:0}.tiles,.cols-3,.cols-4,.metrics{grid-template-columns:1fr}.tile{min-height:0;padding:20px;display:grid;grid-template-columns:40px 1fr;column-gap:15px}.tile svg{width:32px;height:32px;grid-row:span 2;margin:0}.tile h3{font-size:23px;margin-bottom:6px}.tile p{font-size:16px}.metrics strong{font-size:58px}.metrics article{padding:15px 0}.metrics h3{margin:5px 0}.metrics p{margin:8px 0}.flow{grid-auto-flow:row;grid-template-columns:1fr 1fr;gap:15px}.flow-step:after{display:none}.flow-step{padding:18px 15px}.flow-step h3{font-size:20px}.flow-step p{font-size:15px}.welcome-lockup{flex-direction:column;gap:25px;align-items:start}.welcome-lockup img{width:100%}.reading-grid{grid-template-columns:1fr 1fr;gap:10px}.reading-grid>a{padding:18px 12px;font-size:14px;gap:8px}.reading-grid svg{width:23px;min-width:23px}.contact-line{font-size:14px;overflow-wrap:anywhere}.source-links{max-width:100%;text-align:left}.bottomline{flex-direction:column;align-items:start}.bottomline>span:first-child{max-width:100%}.report{font-size:21px}}
@media print{dialog{display:none!important}.organizer h2{font-size:49px}.organizer-content{padding-top:15px}.tiles{display:grid;gap:20px}.cols-3{grid-template-columns:repeat(3,1fr)}.cols-4{grid-template-columns:repeat(4,1fr)}.tile{display:block;min-height:190px;padding:25px 20px}.tile h3{font-size:24px}.tile svg{margin-bottom:20px}.metrics{grid-template-columns:repeat(3,1fr)}.flow{grid-auto-flow:column;grid-template-columns:none;gap:22px}.reading-grid{grid-template-columns:repeat(3,1fr)}.welcome-lockup{flex-direction:row}.welcome-lockup img{width:48%}.bottomline{flex-direction:row}.source-links{max-width:50%;text-align:right}}
'''
base=base.replace('</style>',extra+'</style>')
base=base.replace('</body>','''<dialog id="notesDialog" aria-label="Notas y fuentes"><button id="closeNotes">Cerrar</button><div id="notesContent" class="dialog-heading"></div></dialog>
<script>document.getElementById('notes').addEventListener('click',()=>{const i=Number(document.getElementById('jump').value);document.getElementById('notesContent').innerHTML=document.querySelectorAll('.speaker-note')[i].innerHTML;document.getElementById('notesDialog').showModal();});document.getElementById('closeNotes').addEventListener('click',()=>document.getElementById('notesDialog').close());document.getElementById('notesDialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});</script></body>''')
# Evita que las flechas cambien la presentación al leer el diálogo.
base=base.replace("if(e.altKey||e.ctrlKey", "if(document.querySelector('dialog[open]')||e.altKey||e.ctrlKey")
file.write_text(base)
runpy.run_path(str(ROOT/'crear_onboarding_html.py'))
(ROOT/'onboarding-organizadores.html').write_text((ROOT/'onboarding-cloud-native-lima.html').read_text())
print('15 diapositivas para organizadores. Políticas con enlaces; notas fuera de la vista principal.')
