from slidekit import icon, cards, flow
"""Actualiza el onboarding con contenido mínimo y fuentes para organizadores."""
from pathlib import Path
import re, html, runpy

ROOT=Path(__file__).resolve().parent
S={
 'programa':('Programa CNCF','https://github.com/cncf/communitygroups/blob/main/README.md'),
 'organizadores':('Guía de organizadores','https://github.com/cncf/communitygroups/blob/main/organizers.md'),
 'practicas':('Guía de eventos','https://github.com/cncf/communitygroups/blob/main/best_practices.md'),
 'conducta':('Código de conducta','https://github.com/cncf/foundation/blob/main/code-of-conduct.md'),
 'jurisdiccion':('Alcance y reportes','https://www.cncf.io/conduct/faq/'),
 'marca':('Marca de comunidades','https://github.com/cncf/communitygroups/blob/main/branding.md'),
 'antitrust':('Antitrust LF','https://www.linuxfoundation.org/legal/antitrust-policy'),
 'politica':('Neutralidad política','https://www.cncf.io/political-neutrality-policy/'),
 'politicas':('Índice de políticas CNCF','https://www.cncf.io/policies/'),
}
def sources(keys):return ' · '.join('<a href="'+S[k][1]+'" target="_blank" rel="noopener">'+S[k][0]+' ↗</a>' for k in keys)

slides=[]
def add(title,headline,body,kind='Práctica local propuesta',refs=(),note='',dark=False):slides.append((title,headline,body,kind,refs,note,dark))
add('Bienvenida','Organizar es<br><em>hacer comunidad.</em>', '<div class="cover-grid"><div class="cover-brand"><img src="{{LOGO}}" alt="Cloud Native Lima"><p>El equipo que <strong>hace comunidad.</strong></p><span>Aprender. Conectar. Cuidar.</span></div><div class="cover-invite"><span class="chip">BIENVENIDA AL EQUIPO</span><h3>Tu primera tarea.<br>Nuestro próximo encuentro.</h3><div class="campus-strip"><span>Roles</span><span>Guías</span><span>Acción</span></div><p>Onboarding para nuevos organizadores</p></div></div>', 'Cloud Native Lima · equipo organizador',note='Sesión de inducción para quienes organizarán actividades. Objetivo: salir con responsabilidades, lectura de políticas y una primera tarea acordada. Los cuadros marcados como práctica local son propuestas para el equipo de Lima, no requisitos de CNCF.')
add('Objetivos','Nuestro trabajo, <em>en tres verbos.</em>',cards([('book','Enseñar','Experiencias útiles'),('people','Conectar','Personas y universidades'),('heart','Cuidar','Una comunidad sostenible')]),note='Traducir los objetivos en resultados concretos: una práctica que funcione, una nueva persona que se integre y un equipo que pueda sostener el calendario. No usar únicamente inscripciones como medida de éxito.')
add('Equipo','Liderazgo <em>compartido.</em>','<div class="metrics"><article><strong>2+</strong><h3>Organizadores</h3><p>Recomendación del programa</p></article><article><strong>≤50%</strong><h3>De una empresa</h3><p>Composición del equipo</p></article><article><strong>≤2</strong><h3>Grupos por organizador</h3><p>Límite del programa</p></article></div>','Guía CNCF · recomendaciones y límites',('organizadores',),'La guía recomienda dos o más personas y, como ideal, hasta siete para grupos presenciales o cinco virtuales; las excepciones para capítulos amplios están en el documento. Todos son líderes: repartir funciones sin asumir una jefatura. Revisar también el criterio de residencia o presencia local durante al menos la mitad del año.')
add('Alta de organizadores','El alta tiene <em>un proceso.</em>',flow([('people','Acordar','Con el equipo'),('link','Solicitar','Issue en GitHub'),('check','Confirmar','Términos y respaldo'),('key','Habilitar','Accesos por rol')]),'CNCF: alta · Lima: entrega de accesos',('organizadores',),'Dos rutas: el equipo presenta la solicitud y la persona comenta aceptando los términos; o la persona la presenta y al menos 50% de organizadores confirma su incorporación. La entrega de accesos es una práctica local posterior a la confirmación correspondiente; no se realiza automáticamente con esta presentación. Las bajas también se tramitan por issue y confirmación de la persona.')
add('Responsabilidades','Una función. <em>Un responsable y respaldo.</em>',cards([('mic','Contenido','Ponentes · revisión'),('calendar','Producción','Sede · equipos'),('people','Comunidad','Difusión · bienvenida'),('link','Alianzas','Universidades · apoyos')]),note='Asignar nombres y respaldo antes de cada actividad. Las funciones son una propuesta local. Añadir responsables explícitos de convivencia y finanzas; pueden ser tareas compartidas con las funciones visibles. Registrar acuerdos y entregar accesos por invitación, sin compartir contraseñas.')
add('Reglas del programa','La base de <em>cada meetup.</em>',cards([('heart','Gratuito','Entrada sin cobro'),('globe','OCGroups','Registro del evento'),('calendar','Actividad','No superar 90 días'),('balance','Neutralidad','Contenido independiente')]),'Requisitos del programa CNCF',('programa','practicas'),'La guía exige registro en Open Community Groups y entrada gratuita en los meetups. El README define inactividad al superar 90 días sin eventos. No confundir ese umbral con las condiciones de incentivos: tienen criterios adicionales. La neutralidad debe mantenerse incluso cuando existe patrocinio; su incumplimiento puede conducir a desactivación.',True)
add('Código de conducta','Respeto. <em>Sin excepciones.</em>',cards([('people','Inclusión','Respeta identidades'),('shield','Sin acoso','Ni represalias'),('lock','Privacidad','No divulgar datos')]),'Código de conducta CNCF',('conducta',),'El código cubre espacios y actividades comunitarias, además de conductas dirigidas a participantes en ese contexto. Prohíbe acoso, amenazas, divulgación de información privada sin permiso y represalias. Como organizadores debemos conocerlo y hacerlo visible en nuestras actividades.')
add('Reporte de incidentes','Escuchar → <em>proteger → reportar.</em>',flow([('heart','Escucha','Con discreción'),('shield','Protege','Atiende la seguridad'),('mail','Reporta','Canal correspondiente')])+'<a class="report" href="mailto:conduct@cncf.io">conduct@cncf.io ↗</a>','Canal CNCF · respuesta local propuesta',('conducta','jurisdiccion'),'Para incidentes comunitarios transversales, el código indica conduct@cncf.io. Kubernetes dispone de conduct@kubernetes.io; los eventos producidos por LF usan eventconduct@cncf.io. Un meetup local no es automáticamente un evento producido por LF. Ante peligro inmediato, priorizar seguridad y ayuda de emergencia. Escuchar en privado y conservar información pertinente; no prometer secreto absoluto ni investigar públicamente. La resolución corresponde al equipo con jurisdicción.')
add('Patrocinios','Apoyo con <em>independencia.</em>',cards([('link','Apoyo','Sede · logística'),('book','Contenido','Revisar las charlas'),('balance','Transparencia','Acordar y registrar')]),'Guía CNCF + gestión local',('practicas',),'La guía recomienda revisar presentaciones para evitar discursos de venta y agradecer a patrocinadores. Recomienda no darles más de quince minutos de escenario ni convertirlos en el contenido principal. Propuesta local: documentar aportes, gastos y compromisos; cualquier acceso a datos requiere una revisión separada y no se ofrece como contraprestación automática.')
add('Otras políticas','También debemos <em>conocer estos límites.</em>',cards([('balance','Competencia','No coordinar precios'),('flag','Neutralidad política','Foco en la misión'),('lock','Datos personales','Respetar permisos')]),'Políticas oficiales CNCF / LF',('antitrust','politica','conducta'),'Antitrust: no intercambiar estrategias comerciales sensibles, repartir mercados ni coordinar precios. Usar agenda y actas; si una conversación infringe la política, objetar, retirarse si continúa y dejar constancia o informar al canal legal indicado. La neutralidad política limita campañas ajenas a cloud native; inclusión y accesibilidad tecnológicas sí están alineadas con la misión. Para privacidad, el código prohíbe divulgar información privada sin permiso explícito.')
add('Identidad','Identidad local. <em>Marcas cuidadas.</em>',cards([('globe','Nombre','Cloud Native Lima'),('heart','Identidad','Referencia a la ciudad'),('shield','Marcas ajenas','Sin alteraciones')]),'Guía de marca de comunidades',('marca',),'La guía permite referencias locales y promueve el símbolo común del programa. El nombre recomendado es Cloud Native + ciudad; no usar CNCF como nombre del capítulo. No alterar logos de proyectos; la guía especifica enlazar a sus sitios cuando se usan. Nuestro logo es una propuesta local, no una marca oficial de CNCF ni una aprobación de CNCF. University se presenta como actividad local, sin prometer certificación o acreditación.')
add('Ciclo del evento','Un evento, <em>cuatro momentos.</em>',flow([('calendar','Preparar','Objetivo · sede'),('mic','Validar','Charla · equipos'),('people','Realizar','CoC · asistencia'),('chart','Mejorar','Recursos · retro')]),'Operación local basada en la guía',('practicas',),'Antes de publicar: confirmar responsable, sede, ponentes y presupuesto. Verificar accesibilidad, conectividad y cupo. En la apertura: explicar convivencia, contacto del equipo y tratamiento de fotografías. Después: compartir materiales, contar asistentes reales y hacer retrospectiva. Fechas sugeridas para Lima: preparar cuatro semanas antes y cerrar el seguimiento durante la semana posterior.')
add('Cloud Native University','University: <em>conectar con el campus.</em>',cards([('school','Docente enlace','Objetivo y público'),('book','Práctica guiada','Nivel y requisitos'),('people','Continuidad','Próxima actividad')]),note='Propuesta operativa de Lima para University. Confirmar enlace docente, permisos de sede, accesibilidad y facilitadores; probar el laboratorio y ofrecer alternativa guiada. Medir participación y aprendizaje. No presentar una universidad como aliada hasta acordarlo ni ofrecer certificaciones oficiales sin respaldo.')
add('Primeros 30 días','Tu primer mes <em>organizando.</em>',flow([('book','Leer','Políticas y guías'),('key','Preparar','Rol y accesos'),('people','Acompañar','Un evento del equipo'),('check','Asumir','Una tarea y retro')]),note='Ruta interna sugerida: leer documentos, resolver dudas con el equipo, confirmar incorporación, recibir accesos necesarios y asumir una tarea acotada con respaldo. La disponibilidad real de eventos determina el ritmo. Al cerrar, verificar lectura, rol, responsable de acompañamiento y próximo compromiso.',dark=True)
add('Lecturas y contactos','Antes de organizar, <em>lee las fuentes.</em>','<div class="reading-grid">'+''.join('<a href="'+S[k][1]+'" target="_blank" rel="noopener">'+icon(i)+'<span>'+label+'</span><b>↗</b></a>' for k,i,label in [('organizadores','people','Organizadores'),('programa','globe','Programa'),('conducta','shield','Código de conducta'),('practicas','calendar','Eventos'),('marca','flag','Marca'),('politicas','book','Políticas CNCF')])+'</div><div class="contact-line">Programa: <a href="mailto:community-groups@cncf.io">community-groups@cncf.io</a></div>','Fuentes oficiales · consultadas 25/09/2026',(), 'Las fuentes enlazadas son la referencia vigente; esta presentación es una síntesis de inducción, no sustituye su lectura completa. Para dudas operativas, el programa indica #community-group-organizers en Slack o community-groups@cncf.io. Las reglas de TCG y KCD no se trasladan automáticamente a un grupo regional. Antes del primer evento, el equipo local debe acordar responsables, contactos y herramientas.')

from slidekit import render_document, section
sections=[]
for n,(title,headline,body,kind,refs,note,dark) in enumerate(slides,1):
 sections.append(section(n,title,headline,body,kind,note,dark,sources(refs),'ORGANIZADORES'))
output=render_document('Organizadores · Cloud Native Lima','Onboarding de organizadores',sections)
for name in ['onboarding-organizadores.html','onboarding-cloud-native-lima.html']:
 (ROOT/name).write_text(output)
print(f'{len(slides)} diapositivas · tema compartido Cloud Native Lima.')
